//------------------------------------------------------------------------------
// <auto-generated>
//    このコードはテンプレートから生成されました。
//
//    このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//    このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TestLinqToSql2
{
    #region コンテキスト
    
    /// <summary>
    /// 使用できるメタデータ ドキュメントはありません。
    /// </summary>
    public partial class TestDatabase1Entities : ObjectContext
    {
        #region コンストラクター
    
        /// <summary>
        /// アプリケーション構成ファイルの 'TestDatabase1Entities' セクションにある接続文字列を使用して新しい TestDatabase1Entities オブジェクトを初期化します。
        /// </summary>
        public TestDatabase1Entities() : base("name=TestDatabase1Entities", "TestDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい TestDatabase1Entities オブジェクトを初期化します。
        /// </summary>
        public TestDatabase1Entities(string connectionString) : base(connectionString, "TestDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 新しい TestDatabase1Entities オブジェクトを初期化します。
        /// </summary>
        public TestDatabase1Entities(EntityConnection connection) : base(connection, "TestDatabase1Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分メソッド
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

    
}
